Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/LineLength:
  Max: 130

Metrics/ClassLength:
  Max: 130

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'LICENSE.txt'
    - 'README.md'
    - 'Rakefile'
    - 'bin/*'
    - 'bitex_bot.gemspec'
    - 'settings.rb.sample'
    - 'spec/**/*'
    - 'vendor/**/*'
